apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense1
  # labels of deployment resource
  labels:
    app: backend
    tier: backend
    project: expense1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense1
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense1
    spec:
      containers:
      - name: nginx
        image: nagaleelachandrala/backend:{{ .Values.deployment.version }}
        envFrom:
        - configMapRef:
          name: backend