apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense1
  labels:
    app: mysql
    project: expense1
    tier: db
spec:
  clusterIP: None
  selector:
    app: mysql
    project: expense1
    tier: db
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense1
  labels:
    app: mysql
    project: expense1
    tier: db
spec:
  selector:
    app: mysql
    project: expense1
    tier: db
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306